# Generated by Django 3.2.18 on 2023-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="url",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
