# Generated by Django 3.2.18 on 2023-03-21 13:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('timeblock', models.CharField(choices=[('9 AM', '09:00 - 10:00'), ('11 AM', '11:00 - 12:00'), ('1 PM', '13:00 - 14:00'), ('3 PM', '15:00 - 16:00')], default='9 AM', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
