# Generated by Django 3.2.18 on 2023-03-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Meditation', 'Meditation'), ('Tai Chi', 'Tai Chi')], default='Yoga', max_length=50),
        ),
    ]
