# Generated by Django 3.2.18 on 2023-03-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('A', '09:00 - 10:00'), ('B', '10:30 - 11:30'), ('C', '12:00 - 13:00'), ('D', '13:30 - 14:30'), ('E', '15:00 - 16:00')], default='A', max_length=10),
        ),
    ]
