# Generated by Django 3.2.18 on 2023-03-31 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_remove_account_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="days",
        ),
    ]
