# Generated by Django 3.2.18 on 2023-03-13 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230313_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
