# Generated by Django 3.2.18 on 2023-03-19 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_appointment_timeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
