# Generated by Django 3.2.18 on 2023-04-04 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="date_posted",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
